### ISSUE TITLE
Conda installed libraries are deleted every time the server starts

### ISSUE THREAD

**Issue by dsunol** [ALTERNATIVE-EU/platform-deployment#11]
Whenever you install a library with conda, it install it in/var folder, regardless of the environment you are using. That means 2 things:

- All the libraries are shared. Whenever you install a library, you installed for all env. 
- Every time you close the server, the libraries are deleted.

Thanks!

**Comment by akafazov** [comment]
Some investigation:

- when conda environment is active and user installs a package with **pip**, the package is installed globally (under /var/) and not in the environment folder. This explains why the installed packages are lost after the kernel is restarted.
- using python virtual environment works well

**Comment by akafazov** [comment]
Tasks:

- [x] add usage of python virtualenv to the documentation

**Comment by vikig07** [comment]
Updated docs for python virtual envs - https://github.com/ALTERNATIVE-EU/alternative.github.io/commit/c9eaaf3893514cc7ed5791f66e27ef5bd7d9868a

**Comment by vikig07** [comment]
One way to avoid the packages being deleted is to install `pip` inside the conda environment.

```
conda activate envName
conda install pip
```

After this, packages, installed with `pip` inside the environment, will be only for the specific environment.

**Comment by vikig07** [comment]
I tried multiple config options, but none of them fix the problem with `pip`.

The method I showed above is also given in the official conda docs - https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#installing-non-conda-packages

**Comment by vikig07** [comment]
Updated docs - https://github.com/ALTERNATIVE-EU/alternative.github.io/commit/59f646b3fc02603280b9098ecd8b394446a0b706

**Comment by ignatov17** [comment]
It works according the documentation and installed libraries are not deleted after server restart.
