### ISSUE TITLE
Jupyterlab certificate is expired

### ISSUE THREAD

**Issue by akafazov** [ALTERNATIVE-EU/platform-deployment#14]
https://jupyterhub.ebdfbc2ec9.app.daiteap.com/

**Comment by vikig07** [comment]
I renewed the certificate manually for now. Still looking for the problem in cert-manager.

**Comment by vikig07** [comment]
I created some test certificates and forced them to renew, it seems to be working fine.

Also added some annotations to the prometheus-grafana cert.
