### ISSUE TITLE
Add R-server to the default jupyter kernel

### ISSUE THREAD

**Issue by akafazov** [ALTERNATIVE-EU/platform-deployment#15]
Jupyter users need the R-Server as part of their workflow. It should be available in the default jupyter kernel.

Installation instructions: https://cran.r-project.org/bin/linux/ubuntu/fullREADME.html#installing-r

**Comment by vikig07** [comment]
Added some info about R in the docs - https://github.com/ALTERNATIVE-EU/alternative.github.io/commit/35d7aa24ebb9f5783119c86c9984b2fa022c67f4

**Comment by ignatov17** [comment]
Done, R-server is added.
