### ISSUE TITLE
Installing R Bioconductor 

### ISSUE THREAD

**Issue by xepi90** [ALTERNATIVE-EU/platform-deployment#22]
Hi!

We are trying to install Bioconductor to analyze omics data.  However, we get this error

<img width="444" alt="Captura de pantalla 2023-06-08 102708" src="https://github.com/ALTERNATIVE-EU/platform-deployment/assets/101791817/c03d94f0-fdfc-424f-a634-6e29d33c1ba2">

Can you help us?

Thank you,

Luis

**Comment by vikig07** [comment]
When installing Bioconductor with `BiocManager::install()`, add the path to your R package directory, like so (replace `your_R_package_dir` with the directory name; by default that's `R/x86_64-pc-linux-gnu-library/4.3`):
```
BiocManager::install(lib="/home/jovyan/your_R_package_dir")
```

Updated docs - https://github.com/ALTERNATIVE-EU/alternative.github.io/commit/117e61ca3f21a2ebdd00eace8d10d1a77d62fb41

**Comment by xepi90** [comment]
Sorry, but we continue having issues.  Now we get this warning:

![MicrosoftTeams-image](https://github.com/ALTERNATIVE-EU/platform-deployment/assets/101791817/91da492e-7ebf-499f-be65-2d63b2a10106)

**Comment by vikig07** [comment]
RCurl required a system package, I've added it to the Jupyter image.

The rest of the package installations were failing because they depend on RCurl.

@xepi90 Please try installing again.

**Comment by xepi90** [comment]
Hi! 

We achieve to install some of Bioconductor packages but not all of them.  We think this could be enough.

Thank you
