### ISSUE TITLE
Cannot save an ipynb file

### ISSUE THREAD

**Issue by dsunol** [ALTERNATIVE-EU/platform-deployment#23]
It give me this error:

![image](https://github.com/ALTERNATIVE-EU/platform-deployment/assets/126672106/3dabef7f-ea06-47a4-a548-47d9780018a8)

**Comment by akafazov** [comment]
Can you provide the steps to reproduce the issue?

**Comment by dsunol** [comment]
I guess the problem is because the file is too long. However, it doesn't weight a lot, less than a MB. When I execute some code that draw some graphs, then the file cannot be saved any more and this error appears. But this only happens when there are, aprox +10 graphs. With 5-6 doesn't appear.

**Comment by akafazov** [comment]
Is this in jupyter or in the CKAN platform? How big is the file?

**Comment by dsunol** [comment]
In the jovyan folder, in jupyter. Size aprox 880KB

**Comment by akafazov** [comment]
Hi @dsunol ,

Can you confirm this is fixed for you?

**Comment by dsunol** [comment]
Hi Angel,

So far, now it works.

Thanks!

David
