### ISSUE TITLE
Add 'ln' binary to kernel

### ISSUE THREAD

**Issue by akafazov** [ALTERNATIVE-EU/platform-deployment#25]
I want to use the linux **ln** binary, to create links to **/home/shared** in **/home/jovyan** directory

Tasks:
- [x] add **ln** binary to the kernel
- [x] create symlink **/home/jovyan/shared** pointing to **/home/shared**

**Comment by vikig07** [comment]
@akafazov

The `ln` command works for me currently

**Comment by vikig07** [comment]
I've added the symlink creation in the Jupyter image

Also updated docs - https://github.com/ALTERNATIVE-EU/alternative.github.io/commit/c3c6554bad040b4e57370b2c53f806fb0dc21165

**Comment by akafazov** [comment]
works for me
