### ISSUE TITLE
JupyterHub: console 

### ISSUE THREAD

**Issue by EdoardoVigano** [ALTERNATIVE-EU/platform-deployment#3]
When I try to use the **console** the platform give me this error:
![image](https://user-images.githubusercontent.com/93271669/225848809-ea0ed1e8-a1e2-41b9-8b08-a2c449b758d8.png)

**Comment by vikig07** [comment]
We have increased the available space each user has in Jupyter to 10 GB, so this should be fixed.

**Comment by vikig07** [comment]
@akafazov I believe we can close this now, since it was a storage issue and we have increased the available space for all users.
