### ISSUE TITLE
JupyterHub: Notebook kernels

### ISSUE THREAD

**Issue by EdoardoVigano** [ALTERNATIVE-EU/platform-deployment#4]
1 Notebook: both types of kernels give me this error: 
![image](https://user-images.githubusercontent.com/93271669/225848085-e6995eac-4fed-4e21-99b9-8fbb7b4305ed.png)

but in the folder I haven't this file.

**Comment by vikig07** [comment]
We have increased the available space each user has in Jupyter to 10 GB, so this should be fixed.

**Comment by vikig07** [comment]
@akafazov I believe we can close this now, since it was a storage issue and we have increased the available space for all users.

**Comment by akafazov** [comment]
> @akafazov I believe we can close this now, since it was a storage issue and we have increased the available space for all users.

yes, please close it
