### ISSUE TITLE
Find an error when add a zip file as a dataset on the platform 

### ISSUE THREAD

**Issue by dsunol** [ALTERNATIVE-EU/platform-deployment#41]
Error message:
413 Request Entity Too Large.

The file is less than 2MB. I tried with .zip and .7z, with the same result.

**Comment by akafazov** [comment]
Hi,
We will look into it.

**Comment by akafazov** [comment]
@dsunol the issue should be fixed, please check.

**Comment by dsunol** [comment]
It works now! Thanks!
