### ISSUE TITLE
Cannot save an ipynb file v2

### ISSUE THREAD

**Issue by dsunol** [ALTERNATIVE-EU/platform-deployment#45]
It happens again the same as https://github.com/ALTERNATIVE-EU/platform-deployment/issues/23.

I ploted 2-3 graphs, total size 40KB. Located in jovyan folder.
Maybe some graphs are a bit demanding but it shouldn't be a problem.

**Comment by akafazov** [comment]
Hi, OK we will check why it happens again.

**Comment by darashevcstbg** [comment]
Fixed.
