### ISSUE TITLE
Plotly library doesn't work

### ISSUE THREAD

**Issue by dsunol** [ALTERNATIVE-EU/platform-deployment#47]
Plotly library is used to draw interactive plots (https://plotly.com/python/getting-started/).
I installed it in my environment via pip install. I can import and execute it without any error. However, the output of any plotly function is a simply blank square without the actual plot. 

It seems a common error, but I don't know how to solve it. (https://stackoverflow.com/questions/52771328/plotly-chart-not-showing-in-jupyter-notebook).

Thanks!

**Comment by darashevcstbg** [comment]
Hi @dsunol,
After restarting the jupyter from [here](https://jupyterhub.platform.alternative-project.eu/hub/home), the plot is shown.

![image](https://github.com/ALTERNATIVE-EU/platform-deployment/assets/72433964/c206a0f1-4f79-4cfb-be4a-7b1f8efc38b7)

**Comment by dsunol** [comment]
Hi @darashevcstbg,

It doesn't work for me :(

![image](https://github.com/ALTERNATIVE-EU/platform-deployment/assets/126672106/1fa8978a-19fd-493e-abd1-7b14ef87a79e)

**Comment by darashevcstbg** [comment]
Hi @dsunol,
I found two solutions for this problem:

### Solution 1: Use iFrame for rendering the plotly charts:

1. Add a new cell at the beginning of the notebook, and include the folllowing lines:
    ```py
    import plotly.io as pio
    pio.renderers.default='iframe'
    ```

2. Restart the kernel and run all cells.

### Solution 2: Install the plotly extension on python3 kernel:
1. Create a new empty Python 3 (ipykernel) notebook  ![image](https://github.com/ALTERNATIVE-EU/platform-deployment/assets/72433964/7e6f3ceb-fdcf-401b-a99f-f8012c07ae69)
2. In the cell add the following code and run the cell:
    ```py
    !pip install plotly
    ```
   You should see in the output that `plotly` is successfully installed.
3. Restart the server from [https://jupyterhub.platform.alternative-project.eu/hub/home](https://jupyterhub.platform.alternative-project.eu/hub/home)

4. Restart the kernel and run all cells.


Please let me know if any of these solutions work for you.

**Comment by dsunol** [comment]
Hi @darashevcstbg 

The first solution worked! 

Thanks a lot!
