### ISSUE TITLE
Server not working

### ISSUE THREAD

**Issue by dsunol** [ALTERNATIVE-EU/platform-deployment#48]
From this:

Your server is starting up.

You will be redirected automatically when it's ready for you.
0% Complete

Server requested

until this:

Your server is starting up.

You will be redirected automatically when it's ready for you.
100% Complete

Spawn failed: pod alternative/jupyter-dsunol did not start in 300 seconds!
Event log
Server requested
Spawn failed: pod alternative/jupyter-dsunol did not start in 300 seconds!

Without opening the server.

**Comment by darashevcstbg** [comment]
Hi @dsunol,

The server issue you reported was caused by IONOS restarting nodes during a maintenance window, resulting in some pods failing to start. We have manually restarted the affected pods, and the problem is now resolved. Your server should be operational as expected.
