### ISSUE TITLE
Error importing matplotlib module

### ISSUE THREAD

**Issue by dsunol** [ALTERNATIVE-EU/platform-deployment#55]
I found and estrange bug. In one notebook I couldn't import Matplotlib correctly, while in other notebook I can import it without problem. I have restarted the server and the error persist. 

I have run both notebooks at the same time. 
![image](https://github.com/ALTERNATIVE-EU/platform-deployment/assets/126672106/638700e5-21bc-445f-ad33-521d7f7dcc39)

**Comment by darashevcstbg** [comment]
Hi @dsunol,

It seems there might be a kernel mismatch between your two notebooks. Could you check if you're using the same kernel for both notebooks?

If not, please consider changing the kernel of the first notebook to match the kernel of the second one. Here's a quick guide:

![Kernel Change Guide](https://github.com/ALTERNATIVE-EU/platform-deployment/assets/72433964/a11d48a7-b6f5-4e3b-adb1-c275bc2ee9b4)

My suggestion is to change the kernel of the first notebook to `Conda`. This could potentially resolve the issue you're facing.

**Comment by dsunol** [comment]
Thanks, it was that!
