### ISSUE TITLE
Unable to access to the platform

### ISSUE THREAD

**Issue by dsunol** [ALTERNATIVE-EU/platform-deployment#56]
As I said in the title, I cannot access the platform. When I tried, the system give me this error:

![image](https://github.com/ALTERNATIVE-EU/platform-deployment/assets/126672106/fad4ff21-f9e2-4528-abfb-08e2eb28ebe7)

**Comment by darashevcstbg** [comment]
Hi @dsunol
I have increased the start timeout of JupyterHub, because sometimes the Kubernetes cluster autoscale takes more time that it was set.

**Comment by darashevcstbg** [comment]
Please check again if it is OK now.

**Comment by dsunol** [comment]
Now it works again! thanks!
