### ISSUE TITLE
Library import in Jupyter (python kernel)

### ISSUE THREAD

**Issue by EdoardoVigano** [ALTERNATIVE-EU/platform-deployment#6]
I tried to use a jupyter notebook (on the platform) and if I chose python kernel give me a problem, instead if I use conda this doesn't happen.
![image](https://user-images.githubusercontent.com/93271669/224339747-38251a1a-5261-4082-bb33-db175561f9c0.png)

**Comment by vikig07** [comment]
We're looking into this problem.

**Comment by vikig07** [comment]
The python kernel was using conda instead.

The new version of the Jupyter image is deployed and it should be OK now.

Note: sometimes you may need to restart the kernel after installing/upgrading packages.

**Comment by ignatov17** [comment]
It works well and does not give an error.
